import { ThemeFragment } from '../../../generated/graphql'
import { Layout } from '../../../utils/configTypes'

export interface IntroConfig {
  layoutX: number
  layoutY: number
  layoutWidth: number
  layoutHeight: number
  layoutBorderRadius: number
  titleX: number
  titleY: number
  titleWidth: number
  titleHeight: number
  titleFontSize: number
  userNameX: number
  userNameY: number
  userNameWidth: number
  userNameHeight: number
  userNameFontSize: number
  userInfoX: number
  userInfoY: number
  userInfoWidth: number
  userInfoHeight: number
  userInfoFontSize: number
  logoX: number
  logoY: number
  logoWidth: number
  logoHeight: number
  userMediaLayout?: Layout
}

export const getIntroConfig = ({
  theme,
  layout,
  isShorts,
}: {
  theme: ThemeFragment
  layout: Layout
  isShorts?: boolean
}): IntroConfig => {
  if (!isShorts)
    switch (theme.name) {
      case 'DarkGradient':
        switch (layout) {
          case 'classic':
            return {
              layoutX: 0,
              layoutY: 0,
              layoutWidth: 960,
              layoutHeight: 540,
              layoutBorderRadius: 0,
              titleX: 80,
              titleY: 140,
              titleWidth: 620,
              titleHeight: 172,
              titleFontSize: 72,
              userNameX: 167,
              userNameY: 336,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 167,
              userInfoY: 380,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 80,
              logoY: 344,
              logoWidth: 54,
              logoHeight: 54,
            }
          case 'float-full-right':
            return {
              layoutX: 0,
              layoutY: 0,
              layoutWidth: 960,
              layoutHeight: 540,
              layoutBorderRadius: 0,
              titleX: 80,
              titleY: 120,
              titleWidth: 500,
              titleHeight: 200,
              titleFontSize: 64,
              userNameX: 80,
              userNameY: 336,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 80,
              userInfoY: 380,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 80,
              logoY: 445,
              logoWidth: 54,
              logoHeight: 54,
              userMediaLayout: 'padded-split',
            }
          default:
            return {
              layoutX: 0,
              layoutY: 0,
              layoutWidth: 960,
              layoutHeight: 540,
              layoutBorderRadius: 0,
              titleX: 80,
              titleY: 140,
              titleWidth: 620,
              titleHeight: 172,
              titleFontSize: 72,
              userNameX: 167,
              userNameY: 336,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 167,
              userInfoY: 380,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 80,
              logoY: 344,
              logoWidth: 54,
              logoHeight: 54,
            }
        }
      case 'PastelLines':
        switch (layout) {
          case 'classic':
            return {
              layoutX: 64,
              layoutY: 64,
              layoutWidth: 832,
              layoutHeight: 412,
              layoutBorderRadius: 0,
              titleX: 48,
              titleY: 50,
              titleWidth: 700,
              titleHeight: 160,
              titleFontSize: 72,
              userNameX: 134,
              userNameY: 244,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 134,
              userInfoY: 284,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 48,
              logoY: 248,
              logoWidth: 54,
              logoHeight: 54,
            }
          case 'float-full-right':
            return {
              layoutX: 0,
              layoutY: 0,
              layoutWidth: 960,
              layoutHeight: 540,
              layoutBorderRadius: 0,
              titleX: 80,
              titleY: 64,
              titleWidth: 420,
              titleHeight: 186,
              titleFontSize: 56,
              userNameX: 80,
              userNameY: 316,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 80,
              userInfoY: 360,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 80,
              logoY: 425,
              logoWidth: 54,
              logoHeight: 54,
              userMediaLayout: 'padded-split',
            }
          default:
            return {
              layoutX: 64,
              layoutY: 64,
              layoutWidth: 832,
              layoutHeight: 412,
              layoutBorderRadius: 0,
              titleX: 48,
              titleY: 50,
              titleWidth: 700,
              titleHeight: 160,
              titleFontSize: 72,
              userNameX: 134,
              userNameY: 244,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 134,
              userInfoY: 284,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 48,
              logoY: 248,
              logoWidth: 54,
              logoHeight: 54,
            }
        }
      case 'Cassidoo':
        switch (layout) {
          case 'classic':
            return {
              layoutX: 40,
              layoutY: 40,
              layoutWidth: 880,
              layoutHeight: 460,
              layoutBorderRadius: 16,
              titleX: 40,
              titleY: 120,
              titleWidth: 500,
              titleHeight: 186,
              titleFontSize: 56,
              userNameX: 120,
              userNameY: 350,
              userNameWidth: 816,
              userNameHeight: 40,
              userNameFontSize: 24,
              userInfoX: 120,
              userInfoY: 388,
              userInfoWidth: 816,
              userInfoHeight: 40,
              userInfoFontSize: 24,
              logoX: 40,
              logoY: 348,
              logoWidth: 64,
              logoHeight: 64,
            }
          case 'float-full-right':
            return {
              layoutX: 40,
              layoutY: 109,
              layoutWidth: 523,
              layoutHeight: 323,
              layoutBorderRadius: 16,
              titleX: 40,
              titleY: 80,
              titleWidth: 440,
              titleHeight: 88,
              titleFontSize: 40,
              userNameX: 44,
              userNameY: 200,
              userNameWidth: 400,
              userNameHeight: 30,
              userNameFontSize: 24,
              userInfoX: 44,
              userInfoY: 232,
              userInfoWidth: 816,
              userInfoHeight: 20,
              userInfoFontSize: 18,
              logoX: 44,
              logoY: 270,
              logoWidth: 32,
              logoHeight: 32,
              userMediaLayout: 'float-full-right',
            }
          default:
            return {
              layoutX: 40,
              layoutY: 40,
              layoutWidth: 880,
              layoutHeight: 460,
              layoutBorderRadius: 16,
              titleX: 40,
              titleY: 120,
              titleWidth: 500,
              titleHeight: 186,
              titleFontSize: 56,
              userNameX: 120,
              userNameY: 350,
              userNameWidth: 816,
              userNameHeight: 40,
              userNameFontSize: 24,
              userInfoX: 120,
              userInfoY: 388,
              userInfoWidth: 816,
              userInfoHeight: 40,
              userInfoFontSize: 24,
              logoX: 40,
              logoY: 348,
              logoWidth: 64,
              logoHeight: 64,
            }
        }
      case 'LambdaTest':
        switch (layout) {
          case 'classic':
            return {
              layoutX: 40,
              layoutY: 40,
              layoutWidth: 880,
              layoutHeight: 460,
              layoutBorderRadius: 16,
              titleX: 40,
              titleY: 100,
              titleWidth: 620,
              titleHeight: 172,
              titleFontSize: 72,
              userNameX: 127,
              userNameY: 296,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 127,
              userInfoY: 340,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 40,
              logoY: 304,
              logoWidth: 54,
              logoHeight: 54,
            }
          case 'float-full-right':
            return {
              layoutX: 40,
              layoutY: 40,
              layoutWidth: 880,
              layoutHeight: 460,
              layoutBorderRadius: 0,
              titleX: 40,
              titleY: 80,
              titleWidth: 500,
              titleHeight: 200,
              titleFontSize: 64,
              userNameX: 40,
              userNameY: 296,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 40,
              userInfoY: 340,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 40,
              logoY: 405,
              logoWidth: 54,
              logoHeight: 54,
              userMediaLayout: 'padded-split',
            }
          default:
            return {
              layoutX: 0,
              layoutY: 0,
              layoutWidth: 960,
              layoutHeight: 540,
              layoutBorderRadius: 0,
              titleX: 80,
              titleY: 140,
              titleWidth: 620,
              titleHeight: 172,
              titleFontSize: 72,
              userNameX: 167,
              userNameY: 336,
              userNameWidth: 600,
              userNameHeight: 40,
              userNameFontSize: 32,
              userInfoX: 167,
              userInfoY: 380,
              userInfoWidth: 600,
              userInfoHeight: 57,
              userInfoFontSize: 24,
              logoX: 80,
              logoY: 344,
              logoWidth: 54,
              logoHeight: 54,
            }
        }
      default:
        return {
          layoutX: 0,
          layoutY: 0,
          layoutWidth: 960,
          layoutHeight: 540,
          layoutBorderRadius: 0,
          titleX: 80,
          titleY: 140,
          titleWidth: 620,
          titleHeight: 172,
          titleFontSize: 72,
          userNameX: 167,
          userNameY: 336,
          userNameWidth: 600,
          userNameHeight: 40,
          userNameFontSize: 32,
          userInfoX: 167,
          userInfoY: 380,
          userInfoWidth: 600,
          userInfoHeight: 57,
          userInfoFontSize: 24,
          logoX: 80,
          logoY: 344,
          logoWidth: 54,
          logoHeight: 54,
        }
    }
  return {
    layoutX: 16,
    layoutY: 16,
    layoutWidth: 364,
    layoutHeight: 672,
    layoutBorderRadius: 8,
    titleX: 16,
    titleY: 40,
    titleWidth: 332,
    titleHeight: 532,
    titleFontSize: 32,
    userNameX: 16,
    userNameY: 456,
    userNameWidth: 630,
    userNameHeight: 24,
    userNameFontSize: 20,
    userInfoX: 16,
    userInfoY: 488,
    userInfoWidth: 630,
    userInfoHeight: 20,
    userInfoFontSize: 16,
    logoX: 16,
    logoY: 540,
    logoWidth: 48,
    logoHeight: 48,
  }
}
