#!/bin/sh
RED='\033[0;31m'
NC='\033[0m'
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|hotfix|merge)(\(.+?\))?: .{1,}$"; then
    echo "${RED}Aborting commit. Your commit message is invalid.${NC}" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "${RED}Aborting commit. Your commit message is too long.${NC}" >&2
    exit 1
fi